"""Attribute keys the example sets on its spans, log records and application metrics."""

CASE_ID_ATTRIBUTE = "base14.kyc.case_id"
ACCOUNT_TYPE_ATTRIBUTE = "base14.kyc.account_type"
RESUBMISSION_ROUND_ATTRIBUTE = "base14.kyc.resubmission_round"
OUTCOME_ATTRIBUTE = "base14.kyc.outcome"
ESCALATION_REASON_ATTRIBUTE = "base14.kyc.escalation_reason"
DOCUMENT_TYPE_ATTRIBUTE = "base14.kyc.document_type"
REVIEW_DECISION_ATTRIBUTE = "base14.kyc.review_decision"
ASSESSMENT_DECISION_ATTRIBUTE = "base14.kyc.assessment_decision"
RISK_LEVEL_ATTRIBUTE = "base14.kyc.risk_level"
MISSING_DOCUMENTS_ATTRIBUTE = "base14.kyc.missing_documents"
DOCUMENTS_TO_RESEND_ATTRIBUTE = "base14.kyc.documents_to_resend"
SANCTIONS_RESULT_ATTRIBUTE = "base14.kyc.sanctions.result"
SANCTIONS_SCORE_ATTRIBUTE = "base14.kyc.sanctions.score"
PROMPT_VERSION_ATTRIBUTE = "base14.prompt.version"
ACTIVITY_ATTEMPT_ATTRIBUTE = "base14.temporal.activity.attempt"
HTTP_STATUS_CODE_ATTRIBUTE = "http.response.status_code"
