import os

OTEL_SERVICE_NAME = os.getenv("OTEL_SERVICE_NAME", "python-celery-demo")
OTEL_EXPORTER_OTLP_ENDPOINT = os.getenv("OTEL_EXPORTER_OTLP_ENDPOINT", "http://localhost:4318")
OTEL_EXPORTER_OTLP_PROTOCOL = os.getenv("OTEL_EXPORTER_OTLP_PROTOCOL", "http/protobuf")
OTEL_TRACES_EXPORTER = os.getenv("OTEL_TRACES_EXPORTER", "otlp")
OTEL_METRICS_EXPORTER = os.getenv("OTEL_METRICS_EXPORTER", "otlp")
OTEL_LOGS_EXPORTER = os.getenv("OTEL_LOGS_EXPORTER", "otlp")
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = OTEL_EXPORTER_OTLP_ENDPOINT + "/v1/traces"
OTEL_EXPORTER_OTLP_METRICS_ENDPOINT = OTEL_EXPORTER_OTLP_ENDPOINT + "/v1/metrics"
OTEL_EXPORTER_OTLP_LOGS_ENDPOINT = OTEL_EXPORTER_OTLP_ENDPOINT + "/v1/logs"
