import environ
env = environ.Env(
    OTEL_EXPORTER_OTLP_ENDPOINT=(str, 'localhost:4318')
)
# reading .env file
environ.Env.read_env()
OTEL_EXPORTER_OTLP_ENDPOINT = env('OTEL_EXPORTER_OTLP_ENDPOINT')
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT =env('OTEL_EXPORTER_OTLP_ENDPOINT') + '/v1/traces'
OTEL_EXPORTER_OTLP_TRACES_COMPRESSION= 'gzip'
OTEL_EXPORTER_OTLP_METRICS_COMPRESSION= 'gzip'
OTEL_EXPORTER_OTLP_LOGS_COMPRESSION= 'gzip'
