import environ
env = environ.Env(
    OTEL_SERVICE_NAME=(str, 'python-celery-demo'),
    OTEL_EXPORTER_OTLP_ENDPOINT=(str, 'http://localhost:4318'),
    OTEL_EXPORTER_OTLP_PROTOCOL=(str, 'http/protobuf'),
    OTEL_TRACES_EXPORTER=(str, 'otlp'),
    OTEL_METRICS_EXPORTER=(str, 'otlp'),
    OTEL_LOGS_EXPORTER=(str, 'otlp')
)
environ.Env.read_env()

OTEL_SERVICE_NAME = env('OTEL_SERVICE_NAME')
OTEL_EXPORTER_OTLP_ENDPOINT = env('OTEL_EXPORTER_OTLP_ENDPOINT')
OTEL_EXPORTER_OTLP_PROTOCOL = env('OTEL_EXPORTER_OTLP_PROTOCOL')
OTEL_TRACES_EXPORTER = env('OTEL_TRACES_EXPORTER')
OTEL_METRICS_EXPORTER = env('OTEL_METRICS_EXPORTER')
OTEL_LOGS_EXPORTER = env('OTEL_LOGS_EXPORTER')
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = env('OTEL_EXPORTER_OTLP_ENDPOINT') + '/v1/traces'
OTEL_EXPORTER_OTLP_METRICS_ENDPOINT = env('OTEL_EXPORTER_OTLP_ENDPOINT') + '/v1/metrics'
OTEL_EXPORTER_OTLP_LOGS_ENDPOINT = env('OTEL_EXPORTER_OTLP_ENDPOINT') + '/v1/logs'
