FROM golang:1.27-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o worker ./cmd/worker

FROM alpine:3.23

WORKDIR /app

RUN apk add --no-cache ca-certificates tzdata

RUN adduser -D -g '' appuser
USER appuser

COPY --from=builder /app/worker .

CMD ["./worker"]
