#!/usr/bin/env bash
# Provisions AKS + UAMI + 3 federated credentials + RBAC, fetches kubeconfig,
# then delegates in-cluster install to scripts/install-addons.sh.
# Idempotent: safe to re-run.
#
# Cost: starts ticking at "Bicep deployment" step (~$0.17/hr B4s_v2 + LB).
# Pair with infra/teardown.sh; budget ~$1 for a short demo, more if held longer.

set -euo pipefail

DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    -h|--help) cat <<USAGE
Usage: $(basename "$0") [--dry-run]
  --dry-run   Sanity-check + Azure 'what-if' preview only. No cluster created.
USAGE
      exit 0 ;;
    *) echo "Unknown arg: $arg" >&2; exit 2 ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/.env"
KUBECONFIG_FILE="$ROOT_DIR/kubeconfig.yaml"

REGION="${AZURE_REGION:-centralindia}"
NAME_PREFIX="${NAME_PREFIX:-base14-aks-otel-op}"
# Default Standard_B4s_v2 (cheapest 4 vCPU/16 GB on burstable B-series).
# Override via SYSTEM_NODE_SIZE if your subscription's Bsv2 quota is 0
# (e.g., new PAYG accounts often have 0 Bsv2 quota; D-series is widely
# available). Known-good alternative: Standard_D4s_v6.
SYSTEM_NODE_SIZE="${SYSTEM_NODE_SIZE:-Standard_B4s_v2}"
DATE_STAMP="$(date -u +%Y%m%d)"
RG="${AZURE_RESOURCE_GROUP:-rg-base14-aks-operator-demo-$DATE_STAMP}"
DEPLOYMENT_NAME="aks-otel-op-deploy"

# --- Sanity checks ------------------------------------------------------------
echo "==> Sanity checks"
for cmd in az kubectl helm jq; do
  command -v "$cmd" >/dev/null 2>&1 || { echo "ERROR: $cmd not found" >&2; exit 1; }
done

az account show >/dev/null 2>&1 || { echo "ERROR: az not logged in" >&2; exit 1; }

for var in SCOUT_CLIENT_ID SCOUT_CLIENT_SECRET SCOUT_TOKEN_URL SCOUT_OTLP_ENDPOINT; do
  if [ -z "${!var:-}" ]; then
    echo "ERROR: $var not set. Run: set -a; . ~/.config/base14/scout-otel-config.env; set +a" >&2
    exit 1
  fi
done

[ -f "$SCRIPT_DIR/main.bicep" ] || { echo "ERROR: main.bicep not found" >&2; exit 1; }
[ -d "$ROOT_DIR/manifests" ] || { echo "ERROR: manifests/ dir not found" >&2; exit 1; }

SUBSCRIPTION_ID="$(az account show --query id -o tsv)"
TENANT_ID="$(az account show --query tenantId -o tsv)"

echo "  Subscription: $SUBSCRIPTION_ID"
echo "  Tenant:       $TENANT_ID"
echo "  Region:       $REGION"
echo "  RG:           $RG"
[ "$DRY_RUN" = 1 ] && echo "  Mode:         DRY RUN"

# --- 1. Resource group --------------------------------------------------------
echo "==> Creating/ensuring resource group $RG"
az group create --name "$RG" --location "$REGION" --output none

cat > "$ENV_FILE" <<EOF
# Minimal .env (early-write for teardown safety).
AZURE_RESOURCE_GROUP=$RG
AZURE_REGION=$REGION
AZURE_TENANT_ID=$TENANT_ID
AZURE_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
EOF
chmod 600 "$ENV_FILE"

# --- 2. Validate + deploy Bicep -----------------------------------------------
echo "==> Validating deployment"
az deployment group validate \
  --resource-group "$RG" --name "$DEPLOYMENT_NAME" \
  --template-file "$SCRIPT_DIR/main.bicep" \
  --parameters namePrefix="$NAME_PREFIX" systemNodeSize="$SYSTEM_NODE_SIZE" \
  --output none

if [ "$DRY_RUN" = 1 ]; then
  echo "==> DRY RUN: az deployment group what-if"
  az deployment group what-if --resource-group "$RG" --name "$DEPLOYMENT_NAME" \
    --template-file "$SCRIPT_DIR/main.bicep" \
    --parameters namePrefix="$NAME_PREFIX" systemNodeSize="$SYSTEM_NODE_SIZE"
  echo "==> Dry run complete. RG $RG was created (free); re-run without --dry-run to deploy."
  exit 0
fi

echo "==> Deploying Bicep (10-15 min). Cost meter starts now."
az deployment group create \
  --resource-group "$RG" --name "$DEPLOYMENT_NAME" \
  --template-file "$SCRIPT_DIR/main.bicep" \
  --parameters namePrefix="$NAME_PREFIX" systemNodeSize="$SYSTEM_NODE_SIZE" \
  --mode Incremental --output none

# --- 3. Capture outputs -------------------------------------------------------
echo "==> Capturing deployment outputs"
OUTPUTS_JSON="$(az deployment group show --resource-group "$RG" --name "$DEPLOYMENT_NAME" \
  --query properties.outputs -o json)"

CLUSTER_NAME="$(echo "$OUTPUTS_JSON" | jq -r .clusterName.value)"
CLUSTER_RESOURCE_ID="$(echo "$OUTPUTS_JSON" | jq -r .clusterResourceId.value)"
UAMI_PRINCIPAL_ID="$(echo "$OUTPUTS_JSON" | jq -r .uamiPrincipalId.value)"
UAMI_CLIENT_ID="$(echo "$OUTPUTS_JSON" | jq -r .uamiClientId.value)"

cat > "$ENV_FILE" <<EOF
# Generated by infra/provision.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
AZURE_TENANT_ID=$TENANT_ID
AZURE_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
AZURE_RESOURCE_GROUP=$RG
AZURE_REGION=$REGION
AKS_CLUSTER_NAME=$CLUSTER_NAME
AKS_RESOURCE_ID=$CLUSTER_RESOURCE_ID
AKS_UAMI_CLIENT_ID=$UAMI_CLIENT_ID
AKS_UAMI_PRINCIPAL_ID=$UAMI_PRINCIPAL_ID
ENVIRONMENT=demo
EOF
chmod 600 "$ENV_FILE"

# --- 4. Kubeconfig ------------------------------------------------------------
echo "==> Fetching kubeconfig"
az aks get-credentials --resource-group "$RG" --name "$CLUSTER_NAME" \
  --file "$KUBECONFIG_FILE" --overwrite-existing --output none

export KUBECONFIG="$KUBECONFIG_FILE"
kubectl get nodes >/dev/null 2>&1 || { echo "ERROR: kubectl can't reach cluster" >&2; exit 1; }

# --- 5. Delegate to install-addons.sh -----------------------------------------
echo "==> Installing in-cluster stack (cert-manager, operator, CRs, KSM)"
KUBECONFIG="$KUBECONFIG_FILE" \
  AKS_UAMI_CLIENT_ID="$UAMI_CLIENT_ID" \
  AZURE_SUBSCRIPTION_ID="$SUBSCRIPTION_ID" \
  AZURE_REGION="$REGION" \
  AZURE_RESOURCE_GROUP="$RG" \
  AKS_CLUSTER_NAME="$CLUSTER_NAME" \
  AKS_RESOURCE_ID="$CLUSTER_RESOURCE_ID" \
  ENVIRONMENT=demo \
  "$ROOT_DIR/scripts/install-addons.sh"

echo ""
echo "==> Provisioning complete"
echo "  KUBECONFIG: $KUBECONFIG_FILE"
echo "  .env:       $ENV_FILE"
echo ""
echo "  Verify pods:    kubectl get pods -n otel"
echo "  Sample apps:    scripts/deploy-sample-apps.sh"
echo "  Tear down:      infra/teardown.sh"
