source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.7'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.8', '>= 5.2.8.1'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.4.4', '< 0.6.0'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# JWT authentication
gem 'jwt', '~> 2.7'

# Pagination
gem 'kaminari', '~> 1.2.1'

# Prometheus metrics
# gem 'prometheus_exporter', '~> 2.0'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]

  # Testing helpers
  gem 'factory_bot_rails', '~> 5.2'
  gem 'faker', '~> 2.23'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end


# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Background jobs
gem 'sidekiq', '~> 6.5'
gem 'redis', '~> 4.8'

# OpenTelemetry instrumentation (Ruby 2.7 compatible versions - last versions before Ruby 3.0 requirement)
gem 'opentelemetry-sdk', '>= 1.2.0'
gem 'opentelemetry-exporter-otlp', '>= 0.24.2'

# gem 'opentelemetry-instrumentation-all', '>= 0.33.0'
gem 'opentelemetry-instrumentation-rack', '~> 0.22.1'
gem 'opentelemetry-instrumentation-action_pack', '~> 0.4.1'
gem 'opentelemetry-instrumentation-active_record', '~> 0.4.1'
gem 'opentelemetry-instrumentation-active_support', '~> 0.3.0'
gem 'opentelemetry-instrumentation-sidekiq', '~> 0.23.0'

# Optional
# gem 'opentelemetry-instrumentation-active_job', '~> 0.4.0'
# gem 'opentelemetry-instrumentation-active_model_serializers', '~> 0.19.1'
# gem 'opentelemetry-instrumentation-mysql2', '~> 0.22.0'
# gem 'opentelemetry-instrumentation-redis', '~> 0.24.1'
# gem 'opentelemetry-instrumentation-net_http', '~> 0.21.1'
